namespace ServerSideCharacter
{
	public enum SSCMessageType
	{
		SyncPlayerHealth,
		SyncPlayerMana,
		SyncPlayerBank,
		RequestSaveData,
		RequestRegister,
		RequestSetGroup,
		RequestItem,
		RequestAuth,
		SendLoginPassword,
		SendTimeSet,
		HelpCommand,
		KillCommand,
		ListCommand,
		SummonCommand,
		TPHereCommand,
		ButcherCommand,
		TPCommand,
		TimeCommand,
		RegionCreateCommand,
		RegionRemoveCommand,
		LockPlayer,
		TeleportPalyer,
		ToggleGodMode,
		SetGodMode,
		ServerSideCharacter
	}
}
